function out = psychMetric(x,y,varargin)
% bestsol = psychMetric(x,y,varargin)
%options = struct('lb',         [min(x),0],...
%    'ub',         [max(x),max(x)*5],...
%    'init',       [median(x),mad(x)],...
%    'MaxIter',    1e2,...
%    'MaxFunEvals',1e2,...
%    'TolFun',     1e-8,...
%    'FunEvalNo',  3,...
%    'Display',    'off',...
%    'Mode',       'cumulGauss'
%    'fitx',        linspace(min(x),max(x),100));

% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % 

options = struct(...
    'lb',         [min(x),range(x)/10,0,0],...
    'ub',         [max(x),range(x),1,1],...
    'init',       [median(x),mad(x),1,0],...
    'MaxIter',    1e3,...
    'MaxFunEvals',1e3,...
    'TolFun',     1e-15,...
    'FunEvalNo',  3,...
    'Display',    'off',...
    'Mode',       'cumulGauss',...
    'fitx',       linspace(min(x),max(x),100),...
    'findy',      0.5,...
    'findx',      0.5);
options = checkOptions(options,varargin{:});

% % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % % 
if strcmp(options.Mode,'cumulGauss')
    %fun = @(params,X) normcdf(X, params(1), params(2));
    fun = @(params,X) params(3)*normcdf(X, params(1), params(2))+params(4);
    %lsef = @(params) norm(y - fun(params,x));
    lsef = @(params) nansum((y - fun(params,x)).^2);
end

evalopt = saoptimset('MaxIter',options.MaxIter,'MaxFunEvals',options.MaxFunEvals,'TolFun',options.TolFun,'Display',options.Display);

for t = 1:options.FunEvalNo,
    [sol(t,:),fval(t)] = simulannealbnd(@(params) lsef(params), options.init*rand*0.1, options.lb, options.ub,evalopt);
end
[~,minIdx] = min(fval);
out.sol = sol(minIdx,:);
out.fitx   = options.fitx;
out.fity   = fun(out.sol,options.fitx);
if mean(isnan(y)) > 0.99,
    %warning('y contains too many NAN values');
    out.fity = nan(size(out.fity));
end
out.x      = x;
out.y      = y;

[~,findxIdx] = min(abs(out.fity-options.findx));
out.findx = out.fitx(findxIdx);
out.findy = fun(out.sol,options.findy);


end